services:
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file:
      - ./data/mysql/env.mysql
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - sport-network

  api:
    build:
      context: sport_companion
      dockerfile: Dockerfile
    container_name: module_api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ACTIVE_PROFILE: prod
    ports:
      - "8080:8080"
    networks:
      - sport-network

  npm:
    image: 'jc21/nginx-proxy-manager:2.11.3'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      - DB_MYSQL_HOST=mysql
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=sport_companion
      - DB_MYSQL_PASSWORD=1234
      - DB_MYSQL_NAME = home
    volumes:
      - ./data/npm/data:/data
      - ./data/npm/letsencrypt:/etc/letsencrypt
    networks:
      - sport-network
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - sport-network
    restart: on-failure

networks:
  sport-network:
    driver: bridge

volumes:
  sport_data: