services:
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file:
      - ./data/mysql/env.mysql
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - sport-network

  api:
    build:
      context: sport_companion
      dockerfile: Dockerfile
    container_name: module_api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ACTIVE_PROFILE: prod
    ports:
      - "8080:8080"
    networks:
      - sport-network

networks:
  sport-network:
    driver: bridge

volumes:
  sport_data: