spring:
  config:
    import: classpath:secret.yml

  data:
    redis:
      port: ${PROD.REDIS.PORT}
      host: ${PROD.REDIS.HOST}
      timeout: ${PROD.REDIS.TIMEOUT}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        check_nullability: true
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 1000
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD.DATABASE.URL}
    username: ${PROD.DATABASE.USERNAME}
    password: ${PROD.DATABASE.PASSWORD}
  jwt:
    secret:
      key: ${PROD.AUTH.JWT.SECRET.KEY}
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: ${PROD.AUTH.OAUTH.PROVIDER.KAKAO.authorization-uri}
            token-uri: ${PROD.AUTH.OAUTH.PROVIDER.KAKAO.token-uri}
            user-info-uri: ${PROD.AUTH.OAUTH.PROVIDER.KAKAO.user-info-uri}
            user-name-attribute: ${PROD.AUTH.OAUTH.PROVIDER.KAKAO.user-name-attribute}
        registration:
          kakao:
            admin-key: ${PROD.AUTH.OAUTH.REGISTRATION.KAKAO.admin-key}
            client-id: ${PROD.AUTH.OAUTH.REGISTRATION.KAKAO.client-id}
            client-secret: ${PROD.AUTH.OAUTH.REGISTRATION.KAKAO.client-secret}
            client-authentication-method: ${PROD.AUTH.OAUTH.REGISTRATION.KAKAO.client-authentication-method}
            redirect-uri: ${PROD.AUTH.OAUTH.REGISTRATION.KAKAO.redirect-uri}
            authorization-grant-type: ${PROD.AUTH.OAUTH.REGISTRATION.KAKAO.authorization-grant-type}
            client-name: ${PROD.AUTH.OAUTH.REGISTRATION.KAKAO.client-name}
            scope:
              - ${PROD.AUTH.OAUTH.REGISTRATION.KAKAO.scope[0]}
              - ${PROD.AUTH.OAUTH.REGISTRATION.KAKAO.scope[1]}

cloud:
  aws:
    credentials:
      access-key: ${PROD.S3.ACCESS}
      secret-key: ${PROD.S3.SECRET}
  S3:
    bucket: ${PROD.S3.BUDGET} # bucket 이름을 설정한다.
  region:
    static: ${PROD.S3.REGION} # bucket이 위치한 AWS 리전을 설정한다.
  stack:
    auto: false

selenium:
  server:
    url: http://selenium:4444