spring:
  config:
    import: classpath:secret.yml
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      port: ${DEV.REDIS.PORT}
      host: ${DEV.REDIS.HOST}
      timeout: ${DEV.REDIS.TIMEOUT}

  jpa:
    hibernate:
      # 필요에 따라서 수정 필요
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        check_nullability: true
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 1000
    open-in-view: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV.DATABASE.URL}
    username: ${DEV.DATABASE.USERNAME}
    password: ${DEV.DATABASE.PASSWORD}

  jwt:
    secret:
      key: ${DEV.AUTH.JWT.SECRET.KEY}

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: ${DEV.AUTH.OAUTH.PROVIDER.KAKAO.authorization-uri}
            token-uri: ${DEV.AUTH.OAUTH.PROVIDER.KAKAO.token-uri}
            user-info-uri: ${DEV.AUTH.OAUTH.PROVIDER.KAKAO.user-info-uri}
            user-name-attribute: ${DEV.AUTH.OAUTH.PROVIDER.KAKAO.user-name-attribute}
        registration:
          kakao:
            client-id: ${DEV.AUTH.OAUTH.REGISTRATION.KAKAO.client-id}
            client-secret: ${DEV.AUTH.OAUTH.REGISTRATION.KAKAO.client-secret}
            client-authentication-method: ${DEV.AUTH.OAUTH.REGISTRATION.KAKAO.client-authentication-method}
            redirect-uri: ${DEV.AUTH.OAUTH.REGISTRATION.KAKAO.redirect-uri}
            authorization-grant-type: ${DEV.AUTH.OAUTH.REGISTRATION.KAKAO.authorization-grant-type}
            client-name: ${DEV.AUTH.OAUTH.REGISTRATION.KAKAO.client-name}
            scope:
              - ${DEV.AUTH.OAUTH.REGISTRATION.KAKAO.scope[0]}
              - ${DEV.AUTH.OAUTH.REGISTRATION.KAKAO.scope[1]}
      kakao:
        admin-key: ${DEV.AUTH.OAUTH.REGISTRATION.KAKAO.admin-key}


cloud:
  aws:
    credentials:
      access-key: ${DEV.S3.ACCESS}
      secret-key: ${DEV.S3.SECRET}
  S3:
    bucket: ${DEV.S3.BUDGET} # bucket 이름을 설정한다.
  region:
    static: ${DEV.S3.REGION} # bucket이 위치한 AWS 리전을 설정한다.
  stack:
    auto: false

